# Generated by Django 5.0.3 on 2024-04-17 14:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_user_photo_user_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, default=django.utils.timezone.now, upload_to='users_photos/'),
            preserve_default=False,
        ),
    ]
