version: '3'

services:
  quiz:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - media_file:/app/media
    depends_on:
      - db

  db:
    image: postgres:alpine
    env_file:
      - .db.env

volumes:
  media_file:

